variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 
    SolutionBaseName: 'DFC.Composite.SharedAssets'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.3.0
    endpoint: 'GitHub (ESFA)'

jobs:

- job: BuildDotNetStandard
  displayName: Build-DotNetStandard
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
  - template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)
  - template: AzureDevOpsTemplates/Build/dfc-gulp-build.yml@dfc-devops
    parameters:
      npmfolder: 'DFC.Composite.SharedAssets'
      publishpath: 'wwwroot/ESFA'
      publishname: 'esfa_assets'





